extension:
  - ts
spec: 
  - test/**/*.test.ts
  # - test/multi-user/Users.test.ts
require: 
  - ts-node/register
  - source-map-support/register.js
  - test/tests-global-fixture.ts
loader: ts-node/esm
watch-files:
  - src
  - test
watch-ignore:
  - test/data/
  - test/servers.lock
timeout: 5000
